pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "anujaayare/order-service"
        IMAGE_TAG = "v1.${BUILD_NUMBER}"
        KUBE_NAMESPACE = "monitoring-demo"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git 'https://github.com/your-username/k8s-observability-cicd-platform.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    sh "docker build -t $DOCKER_IMAGE:$IMAGE_TAG ."
                }
            }
        }

        stage('Login to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                }
            }
        }

        stage('Push Image') {
            steps {
                sh "docker push $DOCKER_IMAGE:$IMAGE_TAG"
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh """
                sed -i 's|image:.*|image: $DOCKER_IMAGE:$IMAGE_TAG|' k8s/base/order-service-deployment.yaml
                kubectl apply -f k8s/base/
                """
            }
        }

        stage('Verify Deployment') {
            steps {
                sh "kubectl get pods -n $KUBE_NAMESPACE"
            }
        }
    }

    post {
        success {
            echo "✅ Deployment Successful!"
        }
        failure {
            echo "❌ Deployment Failed!"
        }
    }
}